---
title: "Introduction"
format: html
editor: source
---

### Research Question and Data {-}

For over two centuries, New York City has been the home of some of the most iconic and unique museums in the country. The city boasts an impressive number and variety of museums, attracting visitors from all walks of life. As an art lover myself, I have checked quite a few of the notable New York art museums off my bucket list. However, as I look forward to another spring break trip to the Big Apple, I would like to visit some less well-known museums, perhaps ones a bit more niche or quirky. In this project, I delved into a comprehensive list of all museums in New York City, hoping to better understand this vast array of wonderful institutions.

The original data set I worked with, which I named "museums_raw", was scraped from the website museumhack.com, with a complete list updated in 2023 of all museums in NYC. Museum Hack is a museum tour operator founded in 2013 and headquartered in New York City. The cleaned data set was named "museums". The raw scraped data set includes 145 observations, the number of museums in NYC, and 5 variables, which are name (name of museum), category (category of museum), price (price of adult ticket), address (location of museum), and highlight1 (top "must see" exhibit). In further data cleaning and analysis, additional variables were included such as catmeanprice (mean ticket price for each museum category), pricedifference (difference of individual museum ticket price from the mean ticket price for the category), and zip (zip codes for each museum, extracted from the original address values).

The data used for the leaflet map was obtained from the Github repository on Covid cases in New York City, last updated in October 2022 (repository linked in the "About" page). I used the shape file MODZCTA_2010.shp that lists the modified ZCTA (zip code tabulation areas) of New York City, which allowed me to map the zip codes of the museums in leaflet. The zip codes are referred to as "modified" because it combines ZCTAs with very small populations, thereby providing more regularly sized ZCTAs. I also used the ZCTA-to-MODZCTA.csv file to convert my ZCTAs in the scraped museum addresses into MODZCTA.

In this project, I seek to answer the question of what museums and categories of museums are of greatest interest and most affordable to me, as well as what geographical regions (denoted by zip code) I should visit to maximize the number of museums I can visit within limited time and transportation expenses.

### Methodology {-}
My motivation for researching this topic was my own interest in visiting museums and my upcoming trip to New York in a couple months. As a first-year college student, my main concerns for travel are price and location, as I am limited in budget, which also means I am limited in the scope of locations as transportation is costly as well. Therefore, in this project, I focused on the variables category of museums, ticket price, and zip code. Ideally, I want to maximize the number of museums I visit of categories that interest me while constrained by budget and location. 

My first step was to see how many museums there were per category, which I showed in a bar graph. This allowed me to see the prevalence of museums in categories of interest to me. Next, I created a general histogram showing the distribution of ticket prices for all the museums, so I could see how many fell within reasonable price range for me. Then, I wanted to examine the prices for each category. I used this section to explore the various functions of ggplot, and I came across the lollipop graph and wanted to try it out. For each category, I created a lollipop graph centered at the mean ticket price for those museums, and the lollipop was placed at the actual price for each museum. The label on each lollipop showed the difference between the mean price and actual price, allowing me to see which museums were more affordable in each category. The last section focused on zip codes. I first created a general bar graph listing the number of museums in each zip code, telling me which geographic region had the highest concentration of museums, meaning I could visit the most with the least cost spent on transportation. Then I created a leaflet map in which a user can hover over any NYC zip code and the label would show the zip code number, how many museums are in that zone, and list each of those museums.